version: '3.8'

services:
  mongo:
    image: mongo:8.0.9-noble
    container_name: myMongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      #ME_CONFIG_MONGODB_ADMINPASSWORD: "admin123"
      #ME_CONFIG_MONGODB_SERVER: "testMongo"mongodb://admin:admin123@localhost:27017/sistema_matricula?authSource=admin
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin123@mongo:27017"
      ME_CONFIG_BASICAUTH_USERNAME: "hola"
      ME_CONFIG_BASICAUTH_PASSWORD: "pass"
    depends_on:
      - mongo